run:
  tests: false
  timeout: 5m
linters:
  disable:
    - maligned
    - prealloc
    - rowserrcheck
  disable-all: false
  presets:
    - bugs
  fast: false
issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G106:"
